name: CI

"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Python install
        run: |
          sudo apt-get install plantuml -y
          python -m pip install --upgrade pip
          python -m pip install ltd-conveyor
          python -m pip install -r requirements.txt

      - name: Sphinx build
        run: |
          make html

      - name: Deployment
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --product ts-tma --dir _build/html --gh
