name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install plantuml
        run: |
          sudo apt-get install plantuml -y
      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Sphinx build
        run: |
          make html
      - uses: actions/upload-artifact@v4
        with:
          name: html
          path: _build/html
          retention-days: 1


  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    container: python:3.11
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: html
      - name: Deployment
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ls -laR
          python -m pip install ltd-conveyor
          ltd upload --product ts-tma --dir html --gh
